version: "3"

services:
  nodejs:
    build:
      context: .
      dockerfile: ./docker-back-end.dockerfile
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "8001:8001"
    networks:
      - app-network
    environment:
      SECRET: "${SECRET}"
      PORT: 8001
      NODE_ENV: "production"

  nginx:
    build:
      context: .
      dockerfile: ./docker-reverse-proxy.dockerfile
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
