version: "3"

services:
  nodejs:
    build:
      context: .
      dockerfile: ./docker-back-end.dockerfile
    volumes:
      - ./db:/usr/src/app/prisma
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "8001:8001"
    networks:
      - app-network
    environment:
      SECRET: "${SECRET}"
      PORT: 8001
      NODE_ENV: "production"

  nginx:
    build:
      context: .
      dockerfile: ./docker-reverse-proxy.dockerfile
    container_name: nginx
    volumes: 
     - ./certs:/etc/nginx/certs
    restart: unless-stopped
    ports:
      - "443:443"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
